TYPE=VIEW
query=select `pos112_main`.`ventas_index`.`id` AS `vi_id`,`pos112_main`.`ventas_index`.`sucursal_id` AS `vi_sucursal_id`,`pos112_main`.`ventas_index`.`terminal_id` AS `vi_terminal_id`,`pos112_main`.`ventas_index`.`usuario_id` AS `vi_usuario_id`,`pos112_main`.`ventas_index`.`folio` AS `vi_folio`,`pos112_main`.`ventas_index`.`total` AS `vi_total`,`pos112_main`.`ventas_index`.`efectivo` AS `vi_efectivo`,`pos112_main`.`ventas_index`.`cambio` AS `vi_cambio`,`pos112_main`.`ventas_index`.`fecha` AS `vi_fecha`,`sv`.`id` AS `sv_id`,`sv`.`nombre` AS `sv_nombre`,`sv`.`activo` AS `sv_activo`,`pos112_main`.`ventas_details`.`id` AS `vd_id`,`pos112_main`.`ventas_details`.`sucursal_id` AS `vd_sucursal_id`,`pos112_main`.`ventas_details`.`terminal_id` AS `vd_terminal_id`,`pos112_main`.`ventas_details`.`usuario_id` AS `vd_usuario_id`,`pos112_main`.`ventas_details`.`venta_id` AS `vd_venta_id`,`pos112_main`.`ventas_details`.`producto_id` AS `vd_producto_id`,`pos112_main`.`ventas_details`.`inventario_id` AS `vd_inventario_id`,`pos112_main`.`ventas_details`.`venta_cantidad` AS `vd_venta_cantidad`,`pos112_main`.`ventas_details`.`venta_precio` AS `vd_venta_precio`,`pos112_main`.`ventas_details`.`venta_total` AS `vd_venta_total`,`pos112_main`.`productos`.`id` AS `pr_id`,`pos112_main`.`productos`.`codigobarras` AS `pr_codigobarras`,`pos112_main`.`productos`.`nombre` AS `pr_nombre`,`pos112_main`.`productos`.`departamento` AS `pr_departamento`,`pos112_main`.`productos`.`agranel` AS `pr_agranel`,`pos112_main`.`productos`.`activo` AS `pr_activo`,`pos112_main`.`productos`.`fecha_creado` AS `pr_fecha_creado`,`pos112_main`.`productos`.`fecha_modificado` AS `pr_fecha_modificado`,`sd`.`id` AS `sd_id`,`sd`.`nombre` AS `sd_nombre`,`sd`.`activo` AS `sd_activo` from ((((`pos112_main`.`ventas_details` join `pos112_main`.`ventas_index` on((`pos112_main`.`ventas_index`.`id` = `pos112_main`.`ventas_details`.`venta_id`))) left join `pos112_main`.`productos` on((`pos112_main`.`ventas_details`.`producto_id` = `pos112_main`.`productos`.`id`))) left join `pos112_main`.`sucursales` `sv` on((`pos112_main`.`ventas_index`.`sucursal_id` = `sv`.`id`))) left join `pos112_main`.`sucursales` `sd` on((`pos112_main`.`ventas_details`.`sucursal_id` = `sd`.`id`)))
md5=a9b0f35882b2f882d5d4df5b97d9b8a7
updatable=0
algorithm=0
definer_user=pos112
definer_host=localhost
suid=1
with_check_option=0
timestamp=2019-02-14 00:30:44
create-version=2
source=select `pos112_main`.`ventas_index`.`id` AS `vi_id`,`pos112_main`.`ventas_index`.`sucursal_id` AS `vi_sucursal_id`,`pos112_main`.`ventas_index`.`terminal_id` AS `vi_terminal_id`,`pos112_main`.`ventas_index`.`usuario_id` AS `vi_usuario_id`,`pos112_main`.`ventas_index`.`folio` AS `vi_folio`,`pos112_main`.`ventas_index`.`total` AS `vi_total`,`pos112_main`.`ventas_index`.`efectivo` AS `vi_efectivo`,`pos112_main`.`ventas_index`.`cambio` AS `vi_cambio`,`pos112_main`.`ventas_index`.`fecha` AS `vi_fecha`,`sv`.`id` AS `sv_id`,`sv`.`nombre` AS `sv_nombre`,`sv`.`activo` AS `sv_activo`,`pos112_main`.`ventas_details`.`id` AS `vd_id`,`pos112_main`.`ventas_details`.`sucursal_id` AS `vd_sucursal_id`,`pos112_main`.`ventas_details`.`terminal_id` AS `vd_terminal_id`,`pos112_main`.`ventas_details`.`usuario_id` AS `vd_usuario_id`,`pos112_main`.`ventas_details`.`venta_id` AS `vd_venta_id`,`pos112_main`.`ventas_details`.`producto_id` AS `vd_producto_id`,`pos112_main`.`ventas_details`.`inventario_id` AS `vd_inventario_id`,`pos112_main`.`ventas_details`.`venta_cantidad` AS `vd_venta_cantidad`,`pos112_main`.`ventas_details`.`venta_precio` AS `vd_venta_precio`,`pos112_main`.`ventas_details`.`venta_total` AS `vd_venta_total`,`pos112_main`.`productos`.`id` AS `pr_id`,`pos112_main`.`productos`.`codigobarras` AS `pr_codigobarras`,`pos112_main`.`productos`.`nombre` AS `pr_nombre`,`pos112_main`.`productos`.`departamento` AS `pr_departamento`,`pos112_main`.`productos`.`agranel` AS `pr_agranel`,`pos112_main`.`productos`.`activo` AS `pr_activo`,`pos112_main`.`productos`.`fecha_creado` AS `pr_fecha_creado`,`pos112_main`.`productos`.`fecha_modificado` AS `pr_fecha_modificado`,`sd`.`id` AS `sd_id`,`sd`.`nombre` AS `sd_nombre`,`sd`.`activo` AS `sd_activo` from ((((`pos112_main`.`ventas_details` join `pos112_main`.`ventas_index` on((`pos112_main`.`ventas_index`.`id` = `pos112_main`.`ventas_details`.`venta_id`))) left join `pos112_main`.`productos` on((`pos112_main`.`ventas_details`.`producto_id` = `pos112_main`.`productos`.`id`))) left join `pos112_main`.`sucursales` `sv` on((`pos112_main`.`ventas_index`.`sucursal_id` = `sv`.`id`))) left join `pos112_main`.`sucursales` `sd` on((`pos112_main`.`ventas_details`.`sucursal_id` = `sd`.`id`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `pos112_main`.`ventas_index`.`id` AS `vi_id`,`pos112_main`.`ventas_index`.`sucursal_id` AS `vi_sucursal_id`,`pos112_main`.`ventas_index`.`terminal_id` AS `vi_terminal_id`,`pos112_main`.`ventas_index`.`usuario_id` AS `vi_usuario_id`,`pos112_main`.`ventas_index`.`folio` AS `vi_folio`,`pos112_main`.`ventas_index`.`total` AS `vi_total`,`pos112_main`.`ventas_index`.`efectivo` AS `vi_efectivo`,`pos112_main`.`ventas_index`.`cambio` AS `vi_cambio`,`pos112_main`.`ventas_index`.`fecha` AS `vi_fecha`,`sv`.`id` AS `sv_id`,`sv`.`nombre` AS `sv_nombre`,`sv`.`activo` AS `sv_activo`,`pos112_main`.`ventas_details`.`id` AS `vd_id`,`pos112_main`.`ventas_details`.`sucursal_id` AS `vd_sucursal_id`,`pos112_main`.`ventas_details`.`terminal_id` AS `vd_terminal_id`,`pos112_main`.`ventas_details`.`usuario_id` AS `vd_usuario_id`,`pos112_main`.`ventas_details`.`venta_id` AS `vd_venta_id`,`pos112_main`.`ventas_details`.`producto_id` AS `vd_producto_id`,`pos112_main`.`ventas_details`.`inventario_id` AS `vd_inventario_id`,`pos112_main`.`ventas_details`.`venta_cantidad` AS `vd_venta_cantidad`,`pos112_main`.`ventas_details`.`venta_precio` AS `vd_venta_precio`,`pos112_main`.`ventas_details`.`venta_total` AS `vd_venta_total`,`pos112_main`.`productos`.`id` AS `pr_id`,`pos112_main`.`productos`.`codigobarras` AS `pr_codigobarras`,`pos112_main`.`productos`.`nombre` AS `pr_nombre`,`pos112_main`.`productos`.`departamento` AS `pr_departamento`,`pos112_main`.`productos`.`agranel` AS `pr_agranel`,`pos112_main`.`productos`.`activo` AS `pr_activo`,`pos112_main`.`productos`.`fecha_creado` AS `pr_fecha_creado`,`pos112_main`.`productos`.`fecha_modificado` AS `pr_fecha_modificado`,`sd`.`id` AS `sd_id`,`sd`.`nombre` AS `sd_nombre`,`sd`.`activo` AS `sd_activo` from ((((`pos112_main`.`ventas_details` join `pos112_main`.`ventas_index` on((`pos112_main`.`ventas_index`.`id` = `pos112_main`.`ventas_details`.`venta_id`))) left join `pos112_main`.`productos` on((`pos112_main`.`ventas_details`.`producto_id` = `pos112_main`.`productos`.`id`))) left join `pos112_main`.`sucursales` `sv` on((`pos112_main`.`ventas_index`.`sucursal_id` = `sv`.`id`))) left join `pos112_main`.`sucursales` `sd` on((`pos112_main`.`ventas_details`.`sucursal_id` = `sd`.`id`)))
mariadb-version=100136
