<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.3 setup script
 * Date: Fri, 16 Nov 2018 00:44:29 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: local [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'local';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* Server: rds2 [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'rds2';
$cfg['Servers'][$i]['host'] = 'dbpos112-2.cgygvclmlrzo.us-east-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = ';(^-YF%f+PR];a,$ww[ci,H[JPA8lua9';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 2;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LoginCookieValidity'] = 60*60*24*14; // 60*60*24*7 = one week
?>
