TYPE=VIEW
query=select `pos112_main`.`productos`.`id` AS `p_id`,`pos112_main`.`productos`.`codigobarras` AS `p_codigobarras`,`pos112_main`.`productos`.`nombre` AS `p_nombre`,`pos112_main`.`productos`.`departamento` AS `p_departamento`,`pos112_main`.`productos`.`proveedor` AS `p_proveedor`,`pos112_main`.`productos`.`agranel` AS `p_agranel`,`pos112_main`.`productos`.`activo` AS `p_activo`,`pos112_main`.`productos`.`fecha_creado` AS `p_fecha_creado`,`pos112_main`.`productos`.`fecha_modificado` AS `p_fecha_modificado`,`pos112_main`.`inventario`.`id` AS `inv_id`,`pos112_main`.`inventario`.`sucursal_id` AS `inv_sucursal_id`,`pos112_main`.`inventario`.`terminal_id` AS `inv_terminal_id`,`pos112_main`.`inventario`.`producto_id` AS `inv_producto_id`,`pos112_main`.`inventario`.`entradaCantidad` AS `inv_entradaCantidad`,`pos112_main`.`inventario`.`entradaCosto` AS `inv_entradaCosto`,(`pos112_main`.`inventario`.`entradaCosto` * `pos112_main`.`inventario`.`entradaCantidad`) AS `inv_entradaTotal`,`pos112_main`.`inventario`.`entradaFecha` AS `inv_entradaFecha`,`pos112_main`.`inventario`.`inventarioPrecio` AS `inv_inventarioPrecio`,`pos112_main`.`inventario`.`inventarioMayoreo` AS `inv_inventarioMayoreo`,`pos112_main`.`inventario`.`inventarioExistencia` AS `inv_inventarioExistencia`,`pos112_main`.`inventario`.`inventarioMinimo` AS `inv_inventarioMinimo`,(`pos112_main`.`inventario`.`inventarioExistencia` - `pos112_main`.`inventario`.`inventarioMinimo`) AS `inv_inventarioFaltantes`,`pos112_main`.`inventario`.`ajustePositivo` AS `inv_ajustePositivo`,`pos112_main`.`inventario`.`ajusteNegativo` AS `inv_ajusteNegativo`,`pos112_main`.`inventario`.`ventaCantidad` AS `inv_ventaCantidad`,`pos112_main`.`inventario`.`ventaPrecio` AS `inv_ventaPrecio`,`pos112_main`.`inventario`.`ventaTotal` AS `inv_ventaTotal`,`pos112_main`.`inventario`.`ventaUltima` AS `inv_ventaUltima`,`pos112_main`.`inventario`.`modificado` AS `inv_modificado`,`pos112_main`.`inventario`.`usuario_id` AS `inv_usuario_id`,0 AS `inv_contador`,`pos112_main`.`usuarios`.`email` AS `inv_us_email`,`pos112_main`.`usuarios`.`nombre` AS `inv_us_nombre`,`pos112_main`.`sucursales`.`id` AS `suc_id`,`pos112_main`.`sucursales`.`nombre` AS `suc_nombre` from (((`pos112_main`.`productos` left join `pos112_main`.`inventario` on((`pos112_main`.`productos`.`id` = `pos112_main`.`inventario`.`producto_id`))) left join `pos112_main`.`usuarios` on((`pos112_main`.`usuarios`.`id` = `pos112_main`.`inventario`.`usuario_id`))) left join `pos112_main`.`sucursales` on((`pos112_main`.`sucursales`.`id` = `pos112_main`.`inventario`.`sucursal_id`)))
md5=73842c1e0f90ad1222b3aeb930325d59
updatable=0
algorithm=0
definer_user=pos112
definer_host=localhost
suid=1
with_check_option=0
timestamp=2019-01-13 02:38:45
create-version=2
source=select `productos`.`id` AS `p_id`,`productos`.`codigobarras` AS `p_codigobarras`,`productos`.`nombre` AS `p_nombre`,`productos`.`departamento` AS `p_departamento`,`productos`.`proveedor` AS `p_proveedor`,`productos`.`agranel` AS `p_agranel`,`productos`.`activo` AS `p_activo`,`productos`.`fecha_creado` AS `p_fecha_creado`,`productos`.`fecha_modificado` AS `p_fecha_modificado`,`inventario`.`id` AS `inv_id`,`inventario`.`sucursal_id` AS `inv_sucursal_id`,`inventario`.`terminal_id` AS `inv_terminal_id`,`inventario`.`producto_id` AS `inv_producto_id`,`inventario`.`entradaCantidad` AS `inv_entradaCantidad`,`inventario`.`entradaCosto` AS `inv_entradaCosto`,`inventario`.`entradaCosto` * `inventario`.`entradaCantidad` AS `inv_entradaTotal`,`inventario`.`entradaFecha` AS `inv_entradaFecha`,`inventario`.`inventarioPrecio` AS `inv_inventarioPrecio`,`inventario`.`inventarioMayoreo` AS `inv_inventarioMayoreo`,`inventario`.`inventarioExistencia` AS `inv_inventarioExistencia`,`inventario`.`inventarioMinimo` AS `inv_inventarioMinimo`,`inventario`.`inventarioExistencia` - `inventario`.`inventarioMinimo` AS `inv_inventarioFaltantes`,`inventario`.`ajustePositivo` AS `inv_ajustePositivo`,`inventario`.`ajusteNegativo` AS `inv_ajusteNegativo`,`inventario`.`ventaCantidad` AS `inv_ventaCantidad`,`inventario`.`ventaPrecio` AS `inv_ventaPrecio`,`inventario`.`ventaTotal` AS `inv_ventaTotal`,`inventario`.`ventaUltima` AS `inv_ventaUltima`,`inventario`.`modificado` AS `inv_modificado`,`inventario`.`usuario_id` AS `inv_usuario_id`,0 AS `inv_contador`,`usuarios`.`email` AS `inv_us_email`,`usuarios`.`nombre` AS `inv_us_nombre`,`sucursales`.`id` AS `suc_id`,`sucursales`.`nombre` AS `suc_nombre` from (((`productos` left join `inventario` on(`productos`.`id` = `inventario`.`producto_id`)) left join `usuarios` on(`usuarios`.`id` = `inventario`.`usuario_id`)) left join `sucursales` on(`sucursales`.`id` = `inventario`.`sucursal_id`))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `pos112_main`.`productos`.`id` AS `p_id`,`pos112_main`.`productos`.`codigobarras` AS `p_codigobarras`,`pos112_main`.`productos`.`nombre` AS `p_nombre`,`pos112_main`.`productos`.`departamento` AS `p_departamento`,`pos112_main`.`productos`.`proveedor` AS `p_proveedor`,`pos112_main`.`productos`.`agranel` AS `p_agranel`,`pos112_main`.`productos`.`activo` AS `p_activo`,`pos112_main`.`productos`.`fecha_creado` AS `p_fecha_creado`,`pos112_main`.`productos`.`fecha_modificado` AS `p_fecha_modificado`,`pos112_main`.`inventario`.`id` AS `inv_id`,`pos112_main`.`inventario`.`sucursal_id` AS `inv_sucursal_id`,`pos112_main`.`inventario`.`terminal_id` AS `inv_terminal_id`,`pos112_main`.`inventario`.`producto_id` AS `inv_producto_id`,`pos112_main`.`inventario`.`entradaCantidad` AS `inv_entradaCantidad`,`pos112_main`.`inventario`.`entradaCosto` AS `inv_entradaCosto`,(`pos112_main`.`inventario`.`entradaCosto` * `pos112_main`.`inventario`.`entradaCantidad`) AS `inv_entradaTotal`,`pos112_main`.`inventario`.`entradaFecha` AS `inv_entradaFecha`,`pos112_main`.`inventario`.`inventarioPrecio` AS `inv_inventarioPrecio`,`pos112_main`.`inventario`.`inventarioMayoreo` AS `inv_inventarioMayoreo`,`pos112_main`.`inventario`.`inventarioExistencia` AS `inv_inventarioExistencia`,`pos112_main`.`inventario`.`inventarioMinimo` AS `inv_inventarioMinimo`,(`pos112_main`.`inventario`.`inventarioExistencia` - `pos112_main`.`inventario`.`inventarioMinimo`) AS `inv_inventarioFaltantes`,`pos112_main`.`inventario`.`ajustePositivo` AS `inv_ajustePositivo`,`pos112_main`.`inventario`.`ajusteNegativo` AS `inv_ajusteNegativo`,`pos112_main`.`inventario`.`ventaCantidad` AS `inv_ventaCantidad`,`pos112_main`.`inventario`.`ventaPrecio` AS `inv_ventaPrecio`,`pos112_main`.`inventario`.`ventaTotal` AS `inv_ventaTotal`,`pos112_main`.`inventario`.`ventaUltima` AS `inv_ventaUltima`,`pos112_main`.`inventario`.`modificado` AS `inv_modificado`,`pos112_main`.`inventario`.`usuario_id` AS `inv_usuario_id`,0 AS `inv_contador`,`pos112_main`.`usuarios`.`email` AS `inv_us_email`,`pos112_main`.`usuarios`.`nombre` AS `inv_us_nombre`,`pos112_main`.`sucursales`.`id` AS `suc_id`,`pos112_main`.`sucursales`.`nombre` AS `suc_nombre` from (((`pos112_main`.`productos` left join `pos112_main`.`inventario` on((`pos112_main`.`productos`.`id` = `pos112_main`.`inventario`.`producto_id`))) left join `pos112_main`.`usuarios` on((`pos112_main`.`usuarios`.`id` = `pos112_main`.`inventario`.`usuario_id`))) left join `pos112_main`.`sucursales` on((`pos112_main`.`sucursales`.`id` = `pos112_main`.`inventario`.`sucursal_id`)))
mariadb-version=100136
