/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2020-08-04 16:01:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import xCore.xVariables.*;
import java.text.DecimalFormat;
import xCore.Usuario;
import xCore.Inventario;
import xCore.xOperaciones.OperaInventario;

public final class productoEditar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/estilosymenus.html", Long.valueOf(1548876662000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("xCore.xVariables");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("xCore.Inventario");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("xCore.xOperaciones.OperaInventario");
    _jspx_imports_classes.add("xCore.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Exception ee = null;

    String proLink = OperaVars.getUrl(OperaVars.URL_PRODUCTO_EDITAR);
    
    Usuario usu = new Usuario();
    usu.id = 1;

    OperaInventario op = new OperaInventario();
    Inventario inv_pro = new Inventario();
    inv_pro.producto.activo = 1;
    
    String inv_pro_new_entradaCantidad = "";
    String inv_pro_new_entradaCosto = "";
    String inv_pro_new_inventarioExistencia = "";
    String inv_pro_new_inventarioPrecio = "";
    String inv_pro_new_ProductoBarras = "";
    String inv_pro_new_ProductoNombre = "";
    String inv_pro_new_ProductoActivo = "";

    
    DecimalFormat df2 = OperaUtils.getDefimalFormat();
    
    try {

        if (request.getParameter("p") != null | request.getParameter("pe_id") != null) {

            if ( request.getParameter("p") != null && request.getParameter("p").length() > 0) {
                inv_pro = op.InventarioProductoGet(Integer.parseInt(request.getParameter("p")));
            }
            
            inv_pro_new_ProductoBarras = inv_pro.producto.codigoBarras;
            inv_pro_new_ProductoNombre = inv_pro.producto.nombre;
            inv_pro_new_ProductoActivo = String.valueOf(inv_pro.producto.activo);

            if (request.getParameter("inProCan") != null) {
                inv_pro_new_entradaCantidad = request.getParameter("inProCan");
            }

            if (request.getParameter("inProCos") != null) {
                inv_pro_new_entradaCosto = request.getParameter("inProCos");
            }

            if (request.getParameter("inInvExi") != null) {
                inv_pro_new_inventarioExistencia = request.getParameter("inInvExi");
            }

            if (request.getParameter("inInvPre") != null) {
                inv_pro_new_inventarioPrecio = request.getParameter("inInvPre");
            }

            if (request.getParameter("invProCBa") != null) {
                inv_pro_new_ProductoBarras = request.getParameter("invProCBa");
            }

            if (request.getParameter("invProNom") != null) {
                inv_pro_new_ProductoNombre = request.getParameter("invProNom");
            }

            if (request.getParameter("fep_activo") != null) {
                inv_pro_new_ProductoActivo = request.getParameter("fep_activo").equals("1")?"1":"0";
            }

            if (request.getParameter("bGuardar") != null) {
                if (request.getParameter("bGuardar").compareTo("Guardar") == 0) {
                    //guardarmos tod

                    inv_pro = op.InventarioSet(inv_pro,
                            inv_pro_new_ProductoBarras,
                            inv_pro_new_ProductoNombre,
                            inv_pro_new_ProductoActivo,
                            inv_pro_new_entradaCantidad,
                            inv_pro_new_entradaCosto,
                            inv_pro_new_inventarioExistencia,
                            inv_pro_new_inventarioPrecio,
                            usu);

                    //hasta aqui todo ok!
                    inv_pro_new_entradaCantidad = "";
                    inv_pro_new_entradaCosto = "";
                    inv_pro_new_inventarioExistencia = "";
                    inv_pro_new_inventarioPrecio = "";

                    inv_pro_new_ProductoBarras = inv_pro.producto.codigoBarras;
                    inv_pro_new_ProductoNombre = inv_pro.producto.nombre;
                    inv_pro_new_ProductoActivo = String.valueOf(inv_pro.producto.activo);

                }
            }

        }
    } catch (Exception e) {
        ee = e;
        ee.printStackTrace();
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Inventario</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"estilos.css\">\n");
      out.write("        \n");
      out.write("        <script src=\"libs/jquery-3.3.1.min.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                console.log(\"ready!\");\n");
      out.write("                \n");
      out.write("                if( $( \"#pe_id\" ).val() == '' ){\n");
      out.write("                    $( \"#invProCBa\" ).prop('disabled', false );\n");
      out.write("                    $( \"#invProNom\" ).prop('disabled', false );\n");
      out.write("                    $( \"input[name=fep_activo][value=1]\").prop('checked', true);\n");
      out.write("                    $( \"#btnEditProd\" ).prop('disabled', true );\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                $( \"#btnEditProd\" ).click(function() {\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    if( $( \"#invProCBa\" ).prop('disabled') ){\n");
      out.write("                        $( \"#invProCBa\" ).prop('disabled', false );\n");
      out.write("                        $( \"#invProNom\" ).prop('disabled', false );\n");
      out.write("                        $(\"input[name=fep_activo]\").attr('disabled', false);\n");
      out.write("                        $( \"#btnEditProd\" ).val('Deshacer Edición');\n");
      out.write("                    }else{                    \n");
      out.write("                        $( \"#invProCBa\" ).prop('disabled', true );\n");
      out.write("                        $( \"#invProNom\" ).prop('disabled', true );\n");
      out.write("                        $( \"#invProCBa\" ).val('");
      out.print( inv_pro.producto.codigoBarras );
      out.write("' );\n");
      out.write("                        $( \"#invProNom\" ).val('");
      out.print( inv_pro.producto.nombre );
      out.write("');\n");
      out.write("                        $(\"input[name=fep_activo]\").attr('disabled', true);\n");
      out.write("                        $(\"input[name=fep_activo][value=");
      out.print( inv_pro.producto.activo );
      out.write("]\").prop('checked', true);\n");
      out.write("                        $( \"#btnEditProd\" ).val('Editar Producto');\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    \n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("<!-- Aqui estan los menus -->\n");
      out.write("<h2>\n");
      out.write("    <a href=\"inventario.jsp\">Inventario</a>\n");
      out.write("    <a href=\"productoEditar.jsp\">Nuevo Producto</a>\n");
      out.write("    <a href=\"reportes.jsp\">Reportes</a>\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("    <a href=\"http://52.1.113.227:8080/pos112bTerminal/\" target=\"_blank\">Terminal</a>\n");
      out.write("    \n");
      out.write("</h2>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <h2>Editar Inventario</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
 if (ee != null) {
      out.write("\n");
      out.write("\n");
      out.write("        <h3 style=\"color:red;\">Ocurrio al obtener los recultados:</h3>\n");
      out.write("        <pre> ");
      out.print( ee.getMessage());
      out.write(" </pre>\n");
      out.write("\n");
      out.write("        ");
 }
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"productoEditar.jsp");
      out.print( inv_pro.producto.id != 0 ? "?p=" + inv_pro.producto.id : "");
      out.write("\" method=\"post\">\n");
      out.write("\n");
      out.write("            <input type=\"hidden\" id=\"pe_id\" name=\"pe_id\" value=\"");
      out.print( inv_pro.producto.id != 0 ? inv_pro.producto.id : "");
      out.write("\"/>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <table style=\"width: 450px;\">\n");
      out.write("                <tr>\n");
      out.write("                    <th width=\"20%\">&nbsp;</th>\n");
      out.write("                    <th width=\"40%\">Actual</th>\n");
      out.write("                    <th width=\"40%\">Ajustar</th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Codigo Barras</th>\n");
      out.write("                    <td colspan=\"2\">\n");
      out.write("                        <input type=\"text\" id=\"invProCBa\" name=\"invProCBa\" value=\"");
      out.print( inv_pro_new_ProductoBarras);
      out.write("\" disabled=\"disabled\" style=\"width: 100%\"/>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th >Producto</th>\n");
      out.write("                    <td colspan=\"2\">\n");
      out.write("                        <input type=\"text\" id=\"invProNom\" name=\"invProNom\" value=\"");
      out.print( inv_pro_new_ProductoNombre);
      out.write("\" disabled=\"disabled\"  style=\"width: 100%\"/>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Activo</th>\n");
      out.write("\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"radio\" id=\"fep_activo\" name=\"fep_activo\" value=\"1\"");
 if (inv_pro_new_ProductoActivo.compareTo("1") == 0) {
                                out.print(" checked");
                            } 
      out.write(" disabled=\"disabled\"> Si \n");
      out.write("                        <input type=\"radio\" id=\"fep_activo\" name=\"fep_activo\" value=\"0\"");
 if (inv_pro_new_ProductoActivo.compareTo("0") == 0) {
                                out.print(" checked");
                            }
      out.write(" disabled=\"disabled\"> No\n");
      out.write("                    </td>\n");
      out.write("                    <td><input type=\"button\" id=\"btnEditProd\" value=\"Editar Producto\"></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"3\"><h2>Entrada</h2><hr></th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th width=\"20%\">&nbsp;</th>\n");
      out.write("                    <th width=\"40%\">Última Entrada</th>\n");
      out.write("                    <th width=\"40%\">Realizar Entrada</th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Cantidad</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.entradaCantidad));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" name=\"inProCan\" value=\"");
      out.print( inv_pro_new_entradaCantidad);
      out.write("\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Costo</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.entradaCosto));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" name=\"inProCos\" value=\"");
      out.print( inv_pro_new_entradaCosto);
      out.write("\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Total</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.entradaTotal));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" value=\"\" disabled=\"disabled\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>*Fecha</th>&nbsp;\n");
      out.write("                    <td class=\"numero\">");
      out.print( OperaUtils.getDateFormated(inv_pro.entradaFecha));
      out.write(" Hace ");
      out.print( OperaUtils.getDaysOf(inv_pro.entradaFecha));
      out.write(" días</td>\n");
      out.write("                    <td>&nbsp;</td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"3\"><h2>Inventario</h2><hr></th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th width=\"20%\">&nbsp;</th>\n");
      out.write("                    <th width=\"40%\">Actual</th>\n");
      out.write("                    <th width=\"40%\">Ajuste</th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Existencia</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.inventarioExistencia));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" name=\"inInvExi\" value=\"");
      out.print( inv_pro_new_inventarioExistencia);
      out.write("\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>*Inversion</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.entradaCosto * inv_pro.inventarioExistencia));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" value=\"\" disabled=\"disabled\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Precio público</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.inventarioPrecio));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" name=\"inInvPre\" value=\"");
      out.print( inv_pro_new_inventarioPrecio);
      out.write("\"/></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>*Valor</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.inventarioExistencia * inv_pro.inventarioPrecio));
      out.write("</td>\n");
      out.write("                    <td><input type=\"text\" value=\"\" disabled=\"disabled\"/></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th>Ajustes</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.ajustePositivo));
      out.write("</td>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.ajusteNegativo));
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"3\"><h2>Ventas</h2><hr></th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Cantidad vendida</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.ventaCantidad));
      out.write("</td>\n");
      out.write("                    <td rowspan=\"3\">Al realizar una entrada, el contador de venta se reiniciará</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Total</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.ventaTotal));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Precio promedio</th>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(inv_pro.ventaPrecio));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            &nbsp;<br/>\n");
      out.write("\n");
      out.write("            <input type=\"button\" value=\"Cancelar\">\n");
      out.write("\n");
      out.write("            <input type=\"submit\" name=\"bGuardar\" value=\"Guardar\">\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
