/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-31 01:34:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.Duration;
import java.text.DateFormat;
import java.sql.ResultSet;
import xCore.xOperaciones.OperaConn;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.Statement;
import java.text.DecimalFormat;
import xCore.xVariables.*;
import java.util.List;
import java.util.ArrayList;
import xCore.Inventario;
import xCore.xOperaciones.OperaInventario;

public final class repventas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/estilosymenus.html", Long.valueOf(1548876662000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("xCore.xVariables");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("xCore.Inventario");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.time.Duration");
    _jspx_imports_classes.add("xCore.xOperaciones.OperaConn");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("xCore.xOperaciones.OperaInventario");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Exception eee = null;

    DecimalFormat df2 = OperaUtils.getDefimalFormat();
    DateFormat datefPlain = new SimpleDateFormat("yyyy-MM-dd");

    OperaConn oConn = new OperaConn(false);

    Calendar cal1 = Calendar.getInstance();
    Calendar cal2 = Calendar.getInstance();
    cal2.add(Calendar.DATE, 1);

    if (request.getParameter("rv_fi") != null) {
        cal1.setTime(datefPlain.parse(request.getParameter("rv_fi")));
    }

    if (request.getParameter("rv_ff") != null) {
        cal2.setTime(datefPlain.parse(request.getParameter("rv_ff")));
    }

    Duration diff = Duration.between(cal1.toInstant(), cal2.toInstant());
    if (diff.toDays() <= 0) {
        cal2.setTime(cal1.getTime());
        cal2.add(Calendar.DATE, 1);
    }

    String fi = datefPlain.format(cal1.getTime());
    String ff = datefPlain.format(cal2.getTime());

    String busqueda = "";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Reportes de Ventas</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"estilos.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("<!-- Aqui estan los menus -->\n");
      out.write("<h2>\n");
      out.write("    <a href=\"inventario.jsp\">Inventario</a>\n");
      out.write("    <a href=\"productoEditar.jsp\">Nuevo Producto</a>\n");
      out.write("    <a href=\"reportes.jsp\">Reportes</a>\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("    <a href=\"http://52.1.113.227:8080/pos112bTerminal/\" target=\"_blank\">Terminal</a>\n");
      out.write("    \n");
      out.write("</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
 if (eee != null) {
      out.write("\n");
      out.write("\n");
      out.write("        <h3 style=\"color:red;\">Ocurrio al obtener los recultados:</h3>\n");
      out.write("        <pre> ");
      out.print( eee.getMessage());
      out.write(" </pre>\n");
      out.write("        ");
 }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <h1>Reporte de Ventas</h1>\n");
      out.write("\n");
      out.write("        <p>Periodo: ");


            out.print(OperaUtils.getDateSimpleFormated(cal1.getTime()));

            if (request.getParameter("rv_ff") != null) {
                out.print(" al ");

                out.print(OperaUtils.getDateSimpleFormated(cal2.getTime()));
            }


            
      out.write("</p>\n");
      out.write("        <p>Sucursal: </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Ventas por Sucursal -->\n");
      out.write("        <div>\n");
      out.write("            <h2>Ventas por Sucursal</h2>\n");
      out.write("            <table style=\"width : auto;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th class=\"thSucursal\">Sucursal</th>\n");
      out.write("                        <th class=\"thTotal\">Total</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                ");
                try {

                        busqueda = "SELECT vi_sucursal_id, `sv_nombre`,count(*), sum(`vd_venta_total`) as gTotal from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'"
                                + " group by vi_sucursal_id;";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("sv_nombre"));
      out.write("</td>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
     }

                        busqueda = "SELECT sum(`vd_venta_total`) as gTotal from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th>Total</th>\n");
      out.write("                    <th class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</th>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
     }

                    } catch (Exception e) {
                        e.printStackTrace();
                        out.println("<h3 style=\"color:red;\">Ocurrio al obtener los recultados:" + e.getMessage() + "</h3>");
                    }
                
      out.write("\n");
      out.write("                \n");
      out.write("                \n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <hr/>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--Ventas por Departamento -->\n");
      out.write("        <div>\n");
      out.write("            <h2>Ventas por Departamento</h2>\n");
      out.write("\n");
      out.write("            <table style=\"width : auto;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <th class=\"thDepartamento\">Departamento</th>\n");
      out.write("                        <th class=\"thTotal\">Total</th>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                ");
                try {

                        busqueda = "SELECT pr_departamento, count(*), sum(`vd_venta_total`) as gTotal from `ventas_view`"
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'"
                                + " group by pr_departamento;";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("pr_departamento"));
      out.write("</td>\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                ");
     }

                        busqueda = "SELECT  sum(`vd_venta_total`) as gTotal from `ventas_view`"
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th>Total</th>\n");
      out.write("                    <th class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</th>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
     }

                    } catch (Exception e) {
                        e.printStackTrace();
                        out.println("<h3 style=\"color:red;\">Ocurrio al obtener los recultados:" + e.getMessage() + "</h3>");
                    }
                
      out.write("\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <hr/>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--Ventas por Sucursal, Almacén y departamento -->\n");
      out.write("        <div>\n");
      out.write("            <h2>Ventas por Sucursal, Almacén y departamento</h2>\n");
      out.write("\n");
      out.write("            <table style=\"width : auto;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <th class=\"thSucursal\">Sucursal</th>\n");
      out.write("                        <th class=\"thAlmacen\">Almacen</th>\n");
      out.write("                        <th class=\"thDepartamento\">Departamento</th>\n");
      out.write("                        <th class=\"thTotal\">Total</th>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                ");
                try {

                        busqueda = "SELECT `sv_nombre`, `sd_nombre`,pr_departamento ,count(*), sum(`vd_venta_total`) as gTotal from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'"
                                + " group by vi_sucursal_id,vd_sucursal_id,pr_departamento;";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("sv_nombre"));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("sd_nombre"));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("pr_departamento"));
      out.write("</td>\n");
      out.write("\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                ");
     }

                        busqueda = "SELECT sum(`vd_venta_total`) as gTotal from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"3\">Total</th>\n");
      out.write("                    <th class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</th>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
     }

                    } catch (Exception e) {
                        e.printStackTrace();
                        out.println("<h3 style=\"color:red;\">Ocurrio al obtener los recultados:" + e.getMessage() + "</h3>");
                    }
                
      out.write("\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <hr/>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--Detalle de Ventas -->\n");
      out.write("        \n");
      out.write("        <div>\n");
      out.write("            <h2>Detalle de Ventas</h2>\n");
      out.write("            \n");
      out.write("            <table style=\"width : auto;\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <th class=\"thSucursal\">Sucursal</th>\n");
      out.write("                        <th class=\"thAlmacen\">Almacen</th>\n");
      out.write("                        <th class=\"thDepartamento\">Departamento</th>\n");
      out.write("                        <th class=\"thProductoNombre\">Producto</th>\n");
      out.write("                        <th class=\"thTotal\">Total</th>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                ");
                try {

                        busqueda = "SELECT `sv_nombre`, `sd_nombre`,pr_departamento , pr_nombre ,count(*), sum(`vd_venta_total`) as gTotal "
                                + " from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'"
                                + " GROUP by vi_sucursal_id,vd_sucursal_id,pr_departamento,vd_producto_id ";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("sv_nombre"));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("sd_nombre"));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("pr_departamento"));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( oConn.mgResultSet().getString("pr_nombre"));
      out.write("</td>\n");
      out.write("\n");
      out.write("                    <td class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                ");
     }

                        busqueda = "SELECT sum(`vd_venta_total`) as gTotal from `ventas_view` "
                                + " WHERE `vi_fecha` BETWEEN '" + fi + "' and '" + ff + "'";

                        oConn.mgExecuteQuery(busqueda);

                        while (oConn.mgResultSet().next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"4\">Total</th>\n");
      out.write("                    <th class=\"numero\">");
      out.print( df2.format(oConn.mgResultSet().getDouble("gTotal")));
      out.write("</th>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
     }

                    } catch (Exception e) {
                        e.printStackTrace();
                        out.println("<h3 style=\"color:red;\">Ocurrio al obtener los recultados:" + e.getMessage() + "</h3>");
                    }
                
      out.write("\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
 oConn.mgCloseAll();
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
