/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-31 01:33:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class terminalw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Terminal</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    </head>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <!--<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("    -->    \n");
      out.write("    <script src=\"libs/jquery-3.3.1.min.js\"></script>\n");
      out.write("    <script src=\"libs/jquery.floatThead.min.js\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body,table{margin:0px;padding: 0px;border:0px}\n");
      out.write("        body{font-family:  Helvetica}\n");
      out.write("        h3{font-size: 12px;padding: 4px;}\n");
      out.write("        .ico {\n");
      out.write("            vertical-align: middle;\n");
      out.write("        }\n");
      out.write("        .vemdprolab{color: #2c2626; font-size: small;padding: 3px;width: 97px;display:inline-block}\n");
      out.write("        \n");
      out.write("        .divModificarContenido{background: #a7bae9;height: 282px}\n");
      out.write("        .divModificarContenido > p{margin: 0px 0px 20px 0px;font-size: medium}\n");
      out.write("        .divModificarContenido input[type=\"text\"]{font-size: medium;}\n");
      out.write("        \n");
      out.write("        .divCerrarVenta{background: #a7bae9;height: 282px}\n");
      out.write("        .divCerrarVenta p{margin: 0px 0px 20px 0px;font-size: medium}\n");
      out.write("        .divCerrarVenta input[type=\"text\"]{font-size: medium;}\n");
      out.write("        .divCerrarVenta .vemdprolab{margin: 10px;}\n");
      out.write("        \n");
      out.write("        button{border: 0px;background: #5b90d7;width: 57px;height: 57px;border-radius: 8px;}\n");
      out.write("        button.btnmidd{border: 0px;background: #99bbe9;width: 26px;height: 26px;border-radius: 4px;}\n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        .encabezados {\n");
      out.write("            background: #aac2f0;\n");
      out.write("            font-size: smaller;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .encabezados > div {\n");
      out.write("            padding: 2px;\n");
      out.write("        }\n");
      out.write("        .productos{\n");
      out.write("            margin: 3px 0px 3px 0px;background: #cdd4e2;\n");
      out.write("        }\n");
      out.write("        .productos > div {\n");
      out.write("            background: #aac2f0;\n");
      out.write("            font-size: smaller;\n");
      out.write("            padding: 2px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        h3{margin: 0px;}\n");
      out.write("\n");
      out.write("        /* The Modal (background) */\n");
      out.write("        .modal {\n");
      out.write("            display: none; /* Hidden by default */\n");
      out.write("            position: fixed; /* Stay in place */\n");
      out.write("            z-index: 1; /* Sit on top */\n");
      out.write("            padding-top: 50px; /* Location of the box */\n");
      out.write("            left: 0;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%; /* Full width */\n");
      out.write("            height: 100%; /* Full height */\n");
      out.write("            overflow: auto; /* Enable scroll if needed */\n");
      out.write("            background-color: rgb(0,0,0); /* Fallback color */\n");
      out.write("            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modal Content */\n");
      out.write("        .modal-content {\n");
      out.write("            background-color: #fefefe;\n");
      out.write("            margin: auto;\n");
      out.write("            padding: 1px;\n");
      out.write("            border: 1px solid #888;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 390px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* The Close Button */\n");
      out.write("        .close {\n");
      out.write("            color: #aaaaaa;\n");
      out.write("            float: right;\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .close:hover,\n");
      out.write("        .close:focus {\n");
      out.write("            color: #000;\n");
      out.write("            text-decoration: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <div style=\"width: 320px\">\n");
      out.write("            \n");
      out.write("        \n");
      out.write("        <div style=\"background: #8cabec;width: 320px;\">\n");
      out.write("            <div style=\"display: inline-block; text-align: center;padding: 3px\">\n");
      out.write("                <button>\n");
      out.write("                    <i class=\"fas fa-bars fa-3x\" style=\"padding:2px;\"></i>\n");
      out.write("                </button>\n");
      out.write("                <input id=\"inpBuscarInv\" type=\"text\" style=\"width:160px;height: 40px;border-radius: 5px;vertical-align: top;margin:5px 10px 0px 10px;font-size: 18px;border: 0px;\" placeholder=\"Buscar...\">\n");
      out.write("                <button id=\"btnBuscarPro\">\n");
      out.write("                    <i class=\"fas fa-search fa-3x\" style=\"padding:2px;\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h3>Venta Actual</h3>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("            <div class=\"encabezados\">\n");
      out.write("                <div>\n");
      out.write("                    <div style=\"display: inline-block;width: 200px;\">Producto</div>\n");
      out.write("                    <div style=\"display: inline-block;width: 103px;\">Sucursal</div>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <div style=\"display: inline-block;width: 55px;\">Depto</div>\n");
      out.write("                    <div style=\"display: inline-block;width: 150px;\">Precio x Cantidad</div>\n");
      out.write("                    <div style=\"display: inline-block;width: 103px;\">Total</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        <div id=\"venProductosLista\">\n");
      out.write("\n");
      out.write("                <div id=\"divSinProductos\" style=\"margin: 3px 0px 3px 0px;background: #9cc4ff;color:#100b36;text-align: center;padding: 7px;\">\n");
      out.write("                    <p>Sin productos seleccionados</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("                <div style=\"margin: 3px 0px 3px 0px;background: #cdd4e2\">\n");
      out.write("                    <div >\n");
      out.write("                        <div style=\"display: inline-block;width: 200px;\">ALGON PRODUC</div>\n");
      out.write("                        <div style=\"display: inline-block; width: 103px;\">CHUCHERIAS</div>\n");
      out.write("                    </div>\n");
      out.write("                    <button class=\"btnmidd\" style=\"display: inline-block;\"> <i class=\"fas fa-edit\"></i></button>\n");
      out.write("                    <div style=\"display: inline-block;\">\n");
      out.write("                        <div style=\"display: inline-block;width: 170px;text-align: right;\">1 x $ 50.00</div>\n");
      out.write("                        <div style=\"display: inline-block;width: 103px;text-align: right;\">50.00</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("-->\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div style=\"\">\n");
      out.write("            <hr>\n");
      out.write("            <div style=\"display: inline-block;width: 80px;\">\n");
      out.write("                <button id=\"btnCerrarVenta\">\n");
      out.write("                    <i class=\"fas fa-check-circle fa-3x\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display: inline-block;width: 120px;text-align: right\"><p>Total: $</p></div>\n");
      out.write("            <div style=\"display: inline-block;width: 103px;text-align: right\"><label id=\"lblVentaTotal\">0.00</label></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- The Modal -->\n");
      out.write("        <div id=\"myModal\" class=\"modal\">\n");
      out.write("\n");
      out.write("            <!-- Modal content -->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div>\n");
      out.write("                    <h3>Búsqueda</h3>\n");
      out.write("\n");
      out.write("                    <div class=\"encabezados\">\n");
      out.write("                        <div>\n");
      out.write("                            <div style=\"display: inline-block;width: 77%;\">Producto</div>\n");
      out.write("                            <div style=\"display: inline-block;width: 20%;\">Precio</div>\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"display: inline-block;width: 89%;\">\n");
      out.write("                            <div style=\"display: inline-block;width: 56%;\">Sucursal</div>\n");
      out.write("                            <div style=\"display: inline-block;width: 30%;\">Depto</div>\n");
      out.write("                            <div style=\"display: inline-block;width: 10%;\">Exis</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"busEsperaIco\" style=\"position: absolute;\">\n");
      out.write("                        <i class=\"fas fa-spinner fa-pulse fa-3x\"></i>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"busLista\" style=\"overflow-y:scroll; height:262px;width:315px\">\n");
      out.write("                        <div>\n");
      out.write("                            <div style=\"margin: 3px 0px 3px 0px;background: #c6d9ff;\">\n");
      out.write("                                <div>\n");
      out.write("                                    <div style=\"display: inline-block;width: 77%;\">ALGUN PRODUCTO</div>\n");
      out.write("                                    <div style=\"display: inline-block;width: 20%;\">ESCONDIDO</div>\n");
      out.write("                                </div>\n");
      out.write("                                <div style=\"display: inline-block;\">\n");
      out.write("                                    <div style=\"display: inline-block;width: 56%;\">WHEREVER</div>\n");
      out.write("                                    <div style=\"display: inline-block;width: 30%;text-align: right;\">5</div>\n");
      out.write("                                    <div style=\"display: inline-block;width: 10%;text-align: right;\">$ 6956</div>\n");
      out.write("                                </div>\n");
      out.write("                                <button class=\"btnmidd\" style=\"display: inline-block;\"> <i class=\"fas fa-plus-square\"></i></button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div style=\"margin:5px\">\n");
      out.write("                        <button id=\"btnBuscarBack\">\n");
      out.write("                            <i class=\"fas fa-arrow-alt-circle-left fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- MODIFICAR MODAL -->\n");
      out.write("        <!-- The Modal -->\n");
      out.write("        <div id=\"divModificarModal\" class=\"modal\">\n");
      out.write("\n");
      out.write("            <!-- Modal content -->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                \n");
      out.write("        <h3>Modificar:</h3>\n");
      out.write("        \n");
      out.write("            <div class=\"divModificarContenido\">\n");
      out.write("                <input id=\"inpModProductoId\" type=\"hidden\" value=\"\"/>\n");
      out.write("                <input id=\"inpModProductoIndex\" type=\"hidden\" value=\"\"/>\n");
      out.write("                <p><spam class=\"vemdprolab\">Producto</spam><spam id=\"lblModProNombre\">PRODUCTOE EL QUE SEA</spam></p>\n");
      out.write("                <p><spam class=\"vemdprolab\">Departamento</spam><spam id=\"lblModProDepartamento\">WHEREVER</spam></p>\n");
      out.write("                <p><spam class=\"vemdprolab\">Sucursal</spam><spam id=\"lblModProSucursal\">DONDE SEA</spam></p>\n");
      out.write("\n");
      out.write("                <p><spam  class=\"vemdprolab\">Precio</spam><input id=\"inpModProPrecio\" type=\"text\" style=\"width: 100px;\" disabled=\"disabled\" ></p>\n");
      out.write("                <p><spam  class=\"vemdprolab\">Cantidad</spam><input id=\"inpModProCantidad\" type=\"text\" style=\"width: 100px;\" ></p>\n");
      out.write("                <p><spam  class=\"vemdprolab\">Total</spam><input id=\"inpModProTotal\" type=\"text\" style=\"width: 100px;\"></p>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("                <div style=\"padding: 5px;\">\n");
      out.write("                    <div style=\"display:inline-block; width: 150px;padding: 5px\">\n");
      out.write("                        <button id=\"btnModBack\">\n");
      out.write("                            <i class=\"fas fa-arrow-alt-circle-left fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                        <button id=\"btnModEliminar\">\n");
      out.write("                            <i class=\"fas fa-trash-alt fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display:inline-block; width: 110px;padding: 10px; text-align: right\">\n");
      out.write("                        <button id=\"btnModActualizar\">\n");
      out.write("                            <i class=\"fas fa-check-circle fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- CERRAR VENTA MODAL -->\n");
      out.write("        <!-- The Modal -->\n");
      out.write("        <div id=\"divCerrarModal\" class=\"modal\">\n");
      out.write("\n");
      out.write("            <!-- Modal content -->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                \n");
      out.write("                <h3>Cerrar venta:</h3>\n");
      out.write("                <div class=\"divCerrarVenta\">\n");
      out.write("\n");
      out.write("                    <p> <spam class=\"vemdprolab\">Folio</spam>\n");
      out.write("                        <spam style=\"display:inline-block\">\n");
      out.write("                            <spam id=\"busCerrarEsperaIco\">\n");
      out.write("                                <i class=\"fas fa-spinner fa-pulse\"></i>\n");
      out.write("                            </spam>\n");
      out.write("                        </spam>\n");
      out.write("                        <spam id=\"lblCerrarFolio\"></spam>\n");
      out.write("                        \n");
      out.write("                    </p>\n");
      out.write("\n");
      out.write("                    <p><spam class=\"vemdprolab\" >Total</spam><input id=\"inpCerrarTotal\" type=\"text\" style=\"width: 100px;\" disabled=\"disabled\" ></p>\n");
      out.write("                    <p><spam class=\"vemdprolab\" >Efectivo</spam><input id=\"inpCerrarEfectivo\" type=\"text\" style=\"width: 100px;\" ></p>\n");
      out.write("                    <p><spam class=\"vemdprolab\" >Cambio</spam><input id=\"inpCerrarCambio\" type=\"text\" style=\"width: 100px;\" disabled=\"disabled\"></p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div style=\"padding: 5px;\">\n");
      out.write("                    <div style=\"display:inline-block; width: 150px;padding: 5px\">\n");
      out.write("                        <button id=\"btnCerrarBack\">\n");
      out.write("                            <i class=\"fas fa-arrow-alt-circle-left fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                        <button id=\"btnCerrarNew\" onclick=\"document.location.reload(true);\">\n");
      out.write("                            <i class=\"fas fa-redo-alt fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display:inline-block; width: 110px;padding: 10px; text-align: right\">\n");
      out.write("                        <button id=\"btnCerrarFinalizar\">\n");
      out.write("                            <i class=\"fas fa-check-circle fa-3x\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("// Get the modal\n");
      out.write("        var modal = document.getElementById('myModal');\n");
      out.write("// Get the button that opens the modal\n");
      out.write("        var btn = document.getElementById(\"btnBuscarPro\");\n");
      out.write("// Get the <span> element that closes the modal\n");
      out.write("        var span = document.getElementById(\"btnBuscarBack\");\n");
      out.write("// When the user clicks the button, open the modal \n");
      out.write("        btn.onclick = function () {\n");
      out.write("\n");
      out.write("        modal.style.display = \"block\";\n");
      out.write("        document.getElementById(\"busEsperaIco\").style.display = \"block\";\n");
      out.write("        getBusqueda();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("// When the user clicks on <span> (x), close the modal\n");
      out.write("        span.onclick = function () {\n");
      out.write("        modal.style.display = \"none\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*/ When the user clicks anywhere outside of the modal, close it\n");
      out.write("         window.onclick = function(event) {\n");
      out.write("         if (event.target == modal) {\n");
      out.write("         modal.style.display = \"none\";\n");
      out.write("         }\n");
      out.write("         }\n");
      out.write("         */\n");
      out.write("        function getBusqueda() {\n");
      out.write("        $('#busLista').empty();\n");
      out.write("        //$('#tblFormula').append( '<tr><th scope=\"col\" width=\"50%\">Componentes</th><th scope=\"col\" width=\"13%\">% Peso</th><th scope=\"col\" width=\"14%\">Cantidad</th><th scope=\"col\" width=\"13%\">Unidad</th></tr>');\n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("        url: \"twsj/Inventario?viBuscar=\" + $('#inpBuscarInv').val(),\n");
      out.write("                method: \"post\"\n");
      out.write("        }).done(function (data) {\n");
      out.write("\n");
      out.write("        //console.log(\"Respuesta: \", data);\n");
      out.write("        $.each(data, function (key3, val3) {\n");
      out.write("        //console.log(\"Res: \", key3, val3);\n");
      out.write("        document.getElementById(\"busEsperaIco\").style.display = \"none\";\n");
      out.write("        $.each(val3, function (key, val) {\n");
      out.write("        //console.log(\"Res: \", key, val);\n");
      out.write("        str = \"\";\n");
      out.write("        str += '<div>';\n");
      out.write("        str += '<div style=\"margin: 3px 0px 3px 0px;background: #c6d9ff;\">';\n");
      out.write("        str += '    <div>';\n");
      out.write("        str += '        <div style=\"display: inline-block;width: 77%\">' + val.nombre + '</div>';\n");
      out.write("        str += '        <div style=\"display: inline-block;width: 20%;text-align: right;\"><spam style=\"font-size:x-small;\">$</spam>' + formatter.format( val.precio ) + '</div>';\n");
      out.write("        str += '    </div>';\n");
      out.write("        str += '    <div style=\"display: inline-block;width: 89%;\">';\n");
      out.write("        str += '        <div style=\"display: inline-block;width: 56%;font-size: small;\">' + val.departamento + '</div>';\n");
      out.write("        str += '        <div style=\"display: inline-block;width: 30%;font-size: small;\">' + val.sucursal + '</div>';\n");
      out.write("        str += '        <div style=\"display: inline-block;width: 10%; font-size: small;text-align: right;\">' + val.existencia + '</div>';\n");
      out.write("        \n");
      out.write("        str += '    </div>';\n");
      out.write("        str += '    <button class=\"btnmidd\" style=\"display: inline-block;\" onclick=\"addProductoVenta(\\'' + val.inventario_id + '\\', \\'' + val.nombre + '\\', \\'' + val.departamento + '\\', \\'' + val.sucursal + '\\', \\'' + val.agranel +'\\', \\'' + val.precio + '\\', 1)\" ><i class=\"fas fa-plus-square\"></i></button>';\n");
      out.write("        str += '</div>';\n");
      out.write("        str += '</div>';\n");
      out.write("        $('#busLista').append(str);\n");
      out.write("        });\n");
      out.write("        });\n");
      out.write("        });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var ProductosVentaList = new Array();\n");
      out.write("        \n");
      out.write("        function addProductoVenta(inventario_id, nombre, departamento, sucursal, agranel, precio, cantidad) {\n");
      out.write("            //                   0     1       2             3         4        5       6        7\n");
      out.write("            var prod = [inventario_id, nombre, departamento, sucursal, agranel, precio, cantidad,\"0.00\"];\n");
      out.write("            var paso = true;\n");
      out.write("            ProductosVentaList.forEach(function (item, index, array) {\n");
      out.write("                //console.log(item, index);\n");
      out.write("                if ( item[0] == prod[0] ){\n");
      out.write("                    if (item[4] != \"1\" ){\n");
      out.write("                        item[6] += 1;\n");
      out.write("                    }\n");
      out.write("                    paso = false;\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            if (paso){\n");
      out.write("                ProductosVentaList.push(prod);\n");
      out.write("                \n");
      out.write("                str = \"\";\n");
      out.write("                str += '<div id=\"divProductoItem' + prod[0] +'\" style=\"margin: 3px 0px 3px 0px;background: #cdd4e2\">';\n");
      out.write("                str += '<div >';\n");
      out.write("                str += '    <div style=\"display: inline-block;width: 77%;\">'+ prod[1] +'</div>';\n");
      out.write("                str += '    <div style=\"display: inline-block; width: 20%;font-size: small;\">'+ prod[3] +'</div>';\n");
      out.write("                str += '</div>';\n");
      out.write("                str += '<button class=\"btnmidd\" style=\"display: inline-block;\" onclick=\"modificarProducto('+ inventario_id  +')\"> <i class=\"fas fa-edit\"></i></button>';\n");
      out.write("                str += '<div style=\"display: inline-block;width: 89%;\">';\n");
      out.write("                str += '    <div style=\"display: inline-block;width: 40%;font-size: small;\">'+ prod[2] +'</div>';\n");
      out.write("                str += '    <div style=\"display: inline-block;width: 30%;text-align: right;font-size: small;\"><label id=\"pi_cantidad'+ prod[0] +'\">'+ prod[6] +'</label> x $ '+ formatter.format( prod[5] )+'</div>';\n");
      out.write("                str += '    <div style=\"display: inline-block;width: 20%;text-align: right;\"><label id=\"pi_total'+ prod[0] +'\">'+ prod[7] +'</label></div>';\n");
      out.write("                str += '</div>';\n");
      out.write("                str += '</div>';\n");
      out.write("\n");
      out.write("                $('#venProductosLista').append(str);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById('myModal').style.display = \"none\";\n");
      out.write("            calculaTotal();\n");
      out.write("            \n");
      out.write("            if (prod[4] == \"1\" ){\n");
      out.write("                modificarProducto(prod[0]);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var totalVenta = 0;\n");
      out.write("        function calculaTotal() {\n");
      out.write("            totalVenta = 0;\n");
      out.write("            \n");
      out.write("            if ( ProductosVentaList.length == 0){\n");
      out.write("                document.getElementById('divSinProductos').style.display = \"block\";\n");
      out.write("            }else{\n");
      out.write("                document.getElementById('divSinProductos').style.display = \"none\";\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            ProductosVentaList.forEach(function (item, index, array) {\n");
      out.write("                //console.log(item, index);\n");
      out.write("                //                   0     1       2             3         4        5       6        7\n");
      out.write("                //prod = [inventario_id, nombre, departamento, sucursal, agranel, precio, cantidad,0.00];\n");
      out.write("                item[7] = item[5]*item[6];\n");
      out.write("                $(\"#pi_cantidad\"+ item[0]).text( item[6] );\n");
      out.write("                $(\"#pi_total\"+ item[0]).text( formatter.format( item[7] ) );\n");
      out.write("                totalVenta += item[7];\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(\"#lblVentaTotal\").text( formatter.format( totalVenta ) );\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        function modificarProducto(inventarioID){\n");
      out.write("            \n");
      out.write("            ProductosVentaList.forEach(function (item, index, array) {\n");
      out.write("                if ( item[0] == inventarioID ){\n");
      out.write("                    \n");
      out.write("                    //                   0     1       2             3         4        5       6        7\n");
      out.write("                    //prod = [inventario_id, nombre, departamento, sucursal, agranel, precio, cantidad,0.00];\n");
      out.write("                    $(\"#inpModProductoIndex\").val( index );\n");
      out.write("                \n");
      out.write("                    $(\"#inpModProductoId\").val( ProductosVentaList[index][0] );\n");
      out.write("                    $(\"#lblModProNombre\").text( ProductosVentaList[index][1] );\n");
      out.write("                    $(\"#lblModProDepartamento\").text( ProductosVentaList[index][2] );\n");
      out.write("                    $(\"#lblModProSucursal\").text( ProductosVentaList[index][3] );\n");
      out.write("                    $(\"#inpModProPrecio\").val( ProductosVentaList[index][5] );\n");
      out.write("                    $(\"#inpModProCantidad\").val( ProductosVentaList[index][6] );\n");
      out.write("                    $(\"#inpModProTotal\").val( ProductosVentaList[index][7] );\n");
      out.write("                    \n");
      out.write("                    $(\"#inpModProTotal\").prop('disabled', (ProductosVentaList[index][4]==\"1\"?false:true));\n");
      out.write("                    \n");
      out.write("                    document.getElementById(\"divModificarModal\").style.display = \"block\";\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.getElementById(\"btnModBack\").onclick = function () {\n");
      out.write("            document.getElementById(\"divModificarModal\").style.display = \"none\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.getElementById(\"btnModEliminar\").onclick = function () {\n");
      out.write("            \n");
      out.write("            ProductosVentaList.forEach(function (item, index, array) {\n");
      out.write("                if ( item[0] == $(\"#inpModProductoId\").val() ){\n");
      out.write("                    document.getElementById(\"divModificarModal\").style.display = \"none\";\n");
      out.write("                    \n");
      out.write("                    ProductosVentaList.splice(index, 1);\n");
      out.write("                    \n");
      out.write("                    $(\"#divProductoItem\" + item[0]).remove();\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            calculaTotal();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        document.getElementById(\"btnModActualizar\").onclick = function () {\n");
      out.write("            //                   0     1       2             3         4        5       6        7\n");
      out.write("            //prod = [inventario_id, nombre, departamento, sucursal, agranel, precio, cantidad,0.00];\n");
      out.write("                    \n");
      out.write("            ProductosVentaList.forEach(function (item, index, array) {\n");
      out.write("                if ( item[0] == $(\"#inpModProductoId\").val() ){\n");
      out.write("                    console.log(\"btnModActualizar0\", item);\n");
      out.write("                    document.getElementById(\"divModificarModal\").style.display = \"none\";\n");
      out.write("                    \n");
      out.write("                    item[5] = $(\"#inpModProPrecio\").val();\n");
      out.write("                    item[6] = $(\"#inpModProCantidad\").val();\n");
      out.write("                    item[7] = $(\"#inpModProTotal\").val();\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    console.log(\"btnModActualizar1\", item);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            calculaTotal();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        document.getElementById(\"inpModProCantidad\").oninput = function(){\n");
      out.write("            if ( document.getElementById(\"divModificarModal\").style.display == \"none\") return;\n");
      out.write("            $(\"#inpModProTotal\").val( $(\"#inpModProCantidad\").val() * $(\"#inpModProPrecio\").val() );\n");
      out.write("        };\n");
      out.write("        \n");
      out.write("        document.getElementById(\"inpModProTotal\").oninput = function(){\n");
      out.write("            if ( document.getElementById(\"divModificarModal\").style.display == \"none\") return;\n");
      out.write("            console.log(\"inpModProTotal\",\"ejeck\");\n");
      out.write("            \n");
      out.write("            if ( ProductosVentaList[$(\"#inpModProductoIndex\").val()][4] == \"1\" ){\n");
      out.write("                $(\"#inpModProCantidad\").val( $(\"#inpModProTotal\").val() /  $(\"#inpModProPrecio\").val()  );\n");
      out.write("                console.log(\"inpModProTotal\",\"edit\");\n");
      out.write("            }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        document.getElementById(\"btnCerrarVenta\").onclick = function () {\n");
      out.write("            $(\"#inpCerrarTotal\").val( totalVenta );\n");
      out.write("            $(\"#inpCerrarEfectivo\").val( 0.00 );\n");
      out.write("            $(\"#inpCerrarCambio\").val( 0.00 );\n");
      out.write("            \n");
      out.write("            $(\"#lblCerrarFolio\").text( \"\" );\n");
      out.write("            $(\"#inpCerrarEfectivo\").prop('disabled', false);\n");
      out.write("            document.getElementById(\"btnCerrarBack\").style.visibility = \"visible\"; \n");
      out.write("            document.getElementById(\"btnCerrarNew\").style.visibility = \"hidden\"; \n");
      out.write("            document.getElementById(\"busCerrarEsperaIco\").style.display = \"none\";\n");
      out.write("            document.getElementById(\"btnCerrarFinalizar\").style.visibility = \"visible\"; \n");
      out.write("            \n");
      out.write("            document.getElementById(\"divCerrarModal\").style.display = \"block\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.getElementById(\"inpCerrarEfectivo\").oninput = function(){\n");
      out.write("            if ( document.getElementById(\"divCerrarModal\").style.display == \"none\") return;\n");
      out.write("            $(\"#inpCerrarCambio\").val( $(\"#inpCerrarEfectivo\").val() - $(\"#inpCerrarTotal\").val() );\n");
      out.write("        };\n");
      out.write("        \n");
      out.write("        document.getElementById(\"btnCerrarBack\").onclick = function () {\n");
      out.write("            document.getElementById(\"divCerrarModal\").style.display = \"none\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        document.getElementById(\"btnCerrarFinalizar\").onclick = function () {\n");
      out.write("            document.getElementById(\"busCerrarEsperaIco\").style.display = \"block\";\n");
      out.write("            $.ajax({\n");
      out.write("                type: 'POST',\n");
      out.write("                url: \"twsj/Ventas?viCerrar=1\",\n");
      out.write("                data: { \n");
      out.write("                    total: $(\"#inpCerrarTotal\").val(), \n");
      out.write("                    efectivo: $(\"#inpCerrarEfectivo\").val(), \n");
      out.write("                    cambio: $(\"#inpCerrarCambio\").val(), \n");
      out.write("                    detalle: ProductosVentaList\n");
      out.write("                },\n");
      out.write("                success: function(msg){\n");
      out.write("                    console.log(\"success: \", msg);\n");
      out.write("                    document.getElementById(\"busCerrarEsperaIco\").style.display = \"none\";\n");
      out.write("                }\n");
      out.write("            }).done(function (data) {\n");
      out.write("                \n");
      out.write("                $.each(data, function (key3, val3) {\n");
      out.write("                    if (key3 == \"Error\"){\n");
      out.write("                        alert(\"Error al procesar la venta\");\n");
      out.write("                        console.log(\"Error\", data);\n");
      out.write("                    }else if (key3 == \"folio\"){\n");
      out.write("                        \n");
      out.write("                        $(\"#lblCerrarFolio\").text( val3 );\n");
      out.write("                        $(\"#inpCerrarEfectivo\").prop('disabled', true);\n");
      out.write("                        document.getElementById(\"btnCerrarBack\").style.visibility = \"hidden\"; \n");
      out.write("                        document.getElementById(\"btnCerrarNew\").style.visibility = \"visible\"; \n");
      out.write("                        document.getElementById(\"busCerrarEsperaIco\").style.display = \"none\";\n");
      out.write("                        document.getElementById(\"btnCerrarFinalizar\").style.visibility = \"hidden\"; \n");
      out.write("                    }else{\n");
      out.write("                        alert(\"Respuesta inesperada.\");\n");
      out.write("                        console.log(\"Respuesta: \", data);\n");
      out.write("                    }\n");
      out.write("                \n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        \n");
      out.write(" const formatter = new Intl.NumberFormat('en-US', {\n");
      out.write("  style: 'decimal',\n");
      out.write("  currency: 'USD',\n");
      out.write("  minimumFractionDigits: 2\n");
      out.write("})\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
